volumes:
  postgres_data:
    driver: local

services:
  postgresql:
    image: postgres:16
    shm_size: 1g
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5440:5432
    env_file:
      - .env

  app:
    build: .
    volumes:
      - ./:/workspace
    working_dir: /workspace
    depends_on:
      - postgresql
    command: sleep infinity # keep the container running for vscode to attatch
    env_file:
      - .env
