services:
  app:
    build: .
    volumes:
      - ./:/workspace
    working_dir: /workspace
    ports:
      - 3001:3001
      - 3000:3000
    depends_on:
      - postgresql
    init: true
    command: bash -c "bun run start"
    env_file:
      - .env

  postgresql:
    image: postgres:16
    shm_size: 1g
    restart: always
    volumes:
      - ./pg-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5440:5432
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local
