services:
  app:
    build: .
    container_name: catapulta_indexer_backend
    volumes:
      - ./:/workspace
    working_dir: /workspace
    ports:
      - 3001:3001
      - 3000:3000
    depends_on:
      postgresql:
        condition: service_healthy
    init: true
    command: bash -c "bun run start"
    env_file:
      - .env

  postgresql:
    image: postgres:16
    container_name: catapulta_indexer_postgresql
    shm_size: 1g
    restart: always
    volumes:
      - ./pg-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5440:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
